---
title: "iterations, list columns"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
library(p8105.datasets)

```

Set seed for reproducibility

```{r}
set.seed(12345)
```


```{r}
vec_numeric = 5:8
vec_char = c("My", "name", "is", "Jeff")
vec_logical = c(TRUE, TRUE, TRUE, FALSE)
```

```{r}
l = 
  list(
    vec_numeric = 1:5,
    vec_char = LETTERS,
    matrix = matrix(1:10, nrow = 5, ncol = 2),
    summary = summary(rnorm(100))
  )
```

Accessing lists

```{r}
l$vec_char
l[[2]]
l[["summary"]]
```

### Loops

```{r}
list_norm_samples = 
  list(
    a = rnorm(20, 1, 5),
    b = rnorm(20, 0, 7),
    c = rnorm(20, 20, 1),
    d = rnorm(20, -45, 13)
  )
```
Function from last class
```{r}
mean_and_sd = function(x) {
  
    if(!is.numeric(x)) {
    stop("Argument x should be numeric")} 
  else if (length(x) < 2) {
    stop("Cannot be computed for length 1 vectors")}
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
}
```

Hard to apply a funciton to many inputs ion a list without getting disorganized

```{r}
mean_and_sd(list_norm_samples$a)
mean_and_sd(list_norm_samples$b)
mean_and_sd(list_norm_samples$c)
mean_and_sd(list_norm_samples$d)
```

Creating a For Loop, i is the variable for different interchaning inputs
```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  
  output[[i]] = mean_and_sd(list_norm_samples[[i]])
  
}
```


### use `map`

```{r}

output2 = map(list_norm_samples, mean_and_sd)

#the map function can do a variety of outputs
output_median = map(list_norm_samples, median)
output_summary = map(list_norm_samples, summary)
```

