---
title: "simulations"
output: github_document
---

```{r}
library(tidyverse)
set.seed(12345)
```

Set seed for reproducibility

```{r}
sim_mean_sd = function(n, mu = 2, sigma = 3) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  
  sim_data |> 
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
}
```

```{r}
sim_mean_sd(n =30)
```

Let's try iterating to see how this works under repeated sampling

```{r}
output = vector("list", length = 100)

for (i in 1:100) {
  output[[i]] = sim_mean_sd(n = 30)
}

sim_results = bind_rows(output)

sim_results |> 
  ggplot(aes(x = mu_hat)) + geom_density()
```


use a map function 

```{r}
sim_results_df = 
  expand_grid(
    sample_size = c(30, 60, 120, 240),
    iter = 1:1000
  ) |> 
  mutate(estimate_df = map(sample_size, sim_mean_sd)) |> 
  unnest(estimate_df)

sim_results_df |> 
  mutate(
    sample_size = str_c("n =", sample_size),
    sample_size = fct_inorder(sample_size)) |> 
  ggplot(aes(x = sample_size, y = mu_hat)) + geom_boxplot()
```

```{r Second Version}
sim_mean_sd2 = function(n_obs, true_p = .9) {
  x_vec = rbinom(n = n_obs, size = 1, prob = true_p)
  
  tibble(
    mean = mean(x_vec),
    sd = sd(x_vec)
  )
}

sim_results_df2 = 
  expand_grid(
    sample_size = c(30, 60, 120, 240),
    iter = 1:1000
  ) |> 
  mutate(estimate_df = map(sample_size, sim_mean_sd2)) |> 
  unnest(estimate_df)

sim_results_df2 |> 
  mutate(
    sample_size = str_c("n =", sample_size),
    sample_size = fct_inorder(sample_size)) |> 
  ggplot(aes(x = sample_size, y = mean)) + geom_boxplot()
```


# Simulating for Simple Linear Regression
Goal is to write a funciton that simulates data anad then fits a regression, then reprat to look at the distribution of estimated coefficients.


```{r}
beta_0 = 2
beta_1 = 3

sim_data = 
  tibble(
    x = rnorm(n = 30, mean = 1, sd =1),
    y = beta_0 + beta_1 * x + rnorm(30, mean = 0, sd =1)
  )

ls_fit = lm(y ~ x, data = sim_data)
ls_fit

sim_data |> 
  ggplot(aes(x = x, y = y)) +
  geom_point()

```

Lets wrap this in a function

```{r}
sim_slr = function(n_obs, beta_0 = 2, beta_1 = 3) {
  
  sim_data = 
  tibble(
    x = rnorm(n = n_obs, mean = 1, sd =1),
    y = beta_0 + beta_1 * x + rnorm(n_obs, mean = 0, sd =1)
  )
  
  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
  )
}

sim_slr(n_obs = 30)
```

Run this repeatedly with map

```{r}
new_sim_results_df = 
  expand_grid(
    sample_size = 30, 
    iter = 1:1000
  ) |> 
  mutate(estimate_df = map(sample_size, sim_slr)) |> 
  unnest(estimate_df)

new_sim_results_df

```

```{r}
new_sim_results_df |> 
  summarize(
    mean_b0_hat = mean(beta0_hat),
    mean_b1_hat = mean(beta1_hat)
  )

new_sim_results_df |> 
  ggplot(aes(x = beta0_hat)) + 
  geom_histogram()

new_sim_results_df |> 
  ggplot(aes(x = beta0_hat, y = beta1_hat)) + geom_point()
```

